version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  php-fpm:
    container_name: php-fpm
    build: 
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/project
    depends_on:
      - database

  server:
    container_name: server
    image: nginx:1.23-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/project
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php-fpm

volumes:
  mysql-data: 
